os:
  - linux
  - osx

# See https://docs.travis-ci.com/user/reference/xenial/
dist: xenial
# See https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
osx_image: xcode9.2 # 10.12 w/ macosx10.13 SDK https://doc.qt.io/qt-5.12/supported-platforms.html

language: cpp

compiler:
 - gcc
 - clang

sudo: true

addons:
  apt:
    packages:
     - cmake
     - gperf
     # XCB
     - libfontconfig1-dev # is already the newest version (2.11.94-0ubuntu1.1).
     - libfreetype6-dev # is already the newest version (2.6.1-0.1ubuntu2.3).
     - libx11-dev # is already the newest version (2:1.6.3-1ubuntu2.1).
     - libxext-dev # is already the newest version (2:1.3.3-1).
     - libxfixes-dev
     - libxi-dev
     - libxrender-dev # is already the newest version (1:0.9.9-0ubuntu1).
     - libxcb1-dev # is already the newest version (1.11.1-1ubuntu1).
     - libx11-xcb-dev
     - libxcb-glx0-dev
     - libxkbcommon-x11-dev

    #  - libxcb-keysyms1-dev
    #  - libxcb-image0-dev
    #  - libxcb-shm0-dev
    #  - libxcb-icccm4-dev
    #  - libxcb-sync0-dev
    #  - libxcb-xfixes0-dev
    #  - libxcb-shape0-dev
    #  - libxcb-randr0-dev
    #  - libxcb-render-util0-dev

     - libgl1-mesa-dev
     # Qt WebEngine Required System Libraries
     - libdbus-1-dev
     - libnss3-dev
       # Required libraries for xcb
     - libdrm-dev
     - libxcomposite-dev
     - libxcursor-dev
     - libxi-dev
     - libxrandr-dev
     - libxss-dev # is already the newest version (1:1.2.2-1).
     - libxtst-dev
     # Others
     - khronos-api
     - libcap-dev

script:
 - ./Testing/travisCITest.sh

