name: qt-easy-build
trigger:
  branches:
    include:
    - 5.15.*
jobs:
  - job: Linux
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - checkout: self
        clean: true
        fetchDepth: 5
      - script: |
          sudo apt-get install libclang-dev -y
        displayName: 'Install QDoc Requirements'
      - script: |
          # https://doc-snapshots.qt.io/qt5-5.15/linux.html
          sudo apt-get install build-essential libgl1-mesa-dev -y
        displayName: 'Install Qt Requirements for Development'
      - script: |
          # https://doc.qt.io/qt-5.15/qtwebengine-platform-notes.html#all-platforms
          sudo apt-get install bison flex gperf -y
          # https://doc.qt.io/qt-5.15/qtwebengine-platform-notes.html#linux
          sudo apt-get install libdbus-1-dev libnss3-dev libfontconfig1-dev -y
          # Qt WebEngine for xcb
          sudo apt-get install libdrm-dev libxcomposite-dev libxcursor-dev libxi-dev libxrandr-dev libxss-dev libxtst-dev -y
          # Qt WebEngine other development packages
          sudo apt-get install libegl1-mesa-dev -y # suggested when build failed to find khronos development headers
          sudo apt-get install libcap-dev -y
        displayName: 'Install Qt WebEngine Requirements for Development'
      - bash: |
          set -e
          set -o pipefail

          c++ --version
          cmake --version

          script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

          pushd $script_dir

          $(Build.SourcesDirectory)/Build-qt.sh \
          -c \
          -j 4 \
          -y

          die() {
            echo "Error: $@" 1>&2
            exit 1;
          }

          expected_qt_version="5.15.2"

          ./qt-everywhere-build-$expected_qt_version/bin/qmake --version | grep "Using Qt version $expected_qt_version" || die "Could not run Qt $expected_qt_version"

          popd

  - job: macOS
    timeoutInMinutes: 0
    cancelTimeoutInMinutes: 300
    strategy:
        maxParallel: 4
        matrix:
          # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
          XCode_11:
            imageName: 'macos-10.15'
            xcodeVersion: 11.5
            sdk: 'macosx10.15'
            deploymentTarget: '10.15'
    pool:
      vmImage: $(imageName)
    steps:
      - checkout: self
        clean: true
        fetchDepth: 5
      - script: |
          brew install llvm
        displayName: 'Install QDoc Requirements'
      - bash: |
          set -e
          set -o pipefail

          xcode-select -p
          sudo xcode-select -s /Applications/Xcode_$(xcodeVersion).app/Contents/Developer/
          xcode-select -p
          c++ --version
          cmake --version

          script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

          pushd $script_dir

          $(Build.SourcesDirectory)/Build-qt.sh \
          -c \
          -j 4 \
          -y \
          -s $(sdk) \
          -a x86_64 \
          -d $(deploymentTarget)

          die() {
            echo "Error: $@" 1>&2
            exit 1;
          }

          expected_qt_version="5.15.2"

          ./qt-everywhere-build-$expected_qt_version/bin/qmake --version | grep "Using Qt version $expected_qt_version" || die "Could not run Qt $expected_qt_version"

          popd
